### ISSUE TITLE
DB Firestore

### ISSUE THREAD

**Issue by matutes** [jeremySrgt/lynightProject#1]
bonjour, est-il possible d'accéder à la structure de la base de données firestore? Merci beaucoup

**Comment by jeremySrgt** [comment]
Bonjour, 
la structure de la BDD firestore est assez simple avec une collection d'utilisateur et une collection de boites de nuit

**Comment by matutes** [comment]
désolé, je suis nouveau dans ce domaine, pourriez-vous m'aider un peu comme le seraient les collections?, merci beaucoup
