### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by tenSunFree** [jeremySrgt/lynightProject#4]
No way to run successfully
![2020-04-13_024734](https://user-images.githubusercontent.com/23090085/79077090-4e5feb80-7d31-11ea-92cb-374f07682bda.jpg)

**Comment by jeremySrgt** [comment]
Are you able to run flutter from the command line ?

**Comment by tenSunFree** [comment]
I just downloaded the latest version and it is already working.

Thank you.
